apiVersion: v1
kind: ConfigMap
metadata:
  name: requestdebugger
  namespace: requestdebugger
  labels:
    app.kubernetes.io/name: requestdebugger
data:
  PORT: "5464"
  LOG_PATH: "/tmp/requestHeadersQueryParamsAndBody.log"
  LOG_LEVEL: "debug"
  LOG_FORMAT: "text"
  REQUESTDEBUGGER_URL: ""
